### ISSUE TITLE
volumealsabt only allows fixed 10% volume adjustments?

### ISSUE THREAD

**Issue by TheBigW** [raspberrypi-ui/lxplug-volume#1]
as the title says volumealsabt seems t only allow fixed volume decreases of +-10%. I used previously als commands like:

amixer set PCM 2%+ unmute

which could be adjusted in lxde-pi-rc.xml to any increment/decrement. Even though  volumealsabt is very intuitive to use it would be great if the increment could be adjustable. 10% is quite big...

thanks and regards,
Tobias

**Comment by spl237** [comment]
Unfortunately, the interface by which lxpanel communicates with plugins - which is the way this control is operated - is not particularly flexible; you can only issue single-word commands, without any arguments. So an adjustable increment would require some hackery - such as embedding the increment into the command as all one word, and then parsing it all out later. I'll consider something like this for the future, but bear in mind that your alsamixer commands will still work - I've not removed any support for them - so I suggest you modify the openbox control file and restore your original alsamixer commands.

**Comment by TheBigW** [comment]
Thanks a lot, I just wanted to bring it up. Having it in the future would be great. Problem with customized setups is always in any case that the changes may get lost whenever a new update comes along.
I would be absolutely fine if the default would be  some smaller volume increments for the multimedia volume keys - something like 5% or even 2% - I rather press the key some more times as to adapt manually on the volume bar in case the step was too big.

**Comment by spl237** [comment]
Thinking about it, 5% increments are probably more sensible than 10% ones anyway, and that's a pretty easy change to make; I'll include that in a future release.

**Comment by spl237** [comment]
Changed to 5% increment in latest version - should be in apt within the next day or so.
