### ISSUE TITLE
Unplugging USB sound devices causes 100% load on one core

### ISSUE THREAD

**Issue by BMerz** [raspberrypi-ui/lxplug-volume#10]
When I unplug a USB sound device lxpanel causes 100% load on one core. Even when plugging in again the load persists.
When removing the lxplug-volume plugin from lxpanel the issue is gone. This is reproducible.

I can provide log files if you tell me how to activate logging. Even with G_MESSAGES_DEBUG set to "all" I can not see any debug messages from lxplug-volume in ~/.cache/lxsession/LXDE-pi/run.log.

**Comment by spl237** [comment]
That's a known problem, and there is no known fix - ALSA assumes that devices in use will never disappear underneath it, and it has no means of detecting that it has happened, so if it does happen, ALSA goes into a loop trying to re-establish contact with the no-longer-existent device.

Nothing we can do about it, I'm afraid.

**Comment by BMerz** [comment]
OK, thank you for the information. Then I need to deactivate the Plugin permanently. :-(
