### ISSUE TITLE
Volume icon does not allow the level adjustment with bluetooth devices

### ISSUE THREAD

**Issue by k-ste** [raspberrypi-ui/lxplug-volume#11]
I don't know if it depends on the volumealsabt plugin, with Raspberry Pi4 and the latest Pi OS the volume icon does not allow the level adjustment with bluetooth devices, the audio output on bluetooth works correctly, and it is possible to adjust the levels from pulse audio but the "volume alsa bt" icon after connecting the bluetooth device disables the control and displays a red x.
Tested with Huawei Freelace and Voiis Stereo.
With the hdmi and jack outputs everything works correctly.

**Comment by spl237** [comment]
If you are running pulseaudio, the volume plugin will not connect to Bluetooth devices; Bluetooth can only connect to one of pulseaudio or bluealsa at a time; the plugin uses bluealsa. If you want to use the volumealsabt plugin, you need to uninstall pulseaudio.

**Comment by k-ste** [comment]
OK thanks,
