### ISSUE TITLE
volumealsabt doesn't unmute

### ISSUE THREAD

**Issue by fliperama00** [raspberrypi-ui/lxplug-volume#4]
When I mute the audio, using the middle click on the icon, or via the shortcut, it is impossible to unmute by the same way. I could only unmute via pavucontrol

**Comment by spl237** [comment]
Works as intended for me here - what audio device are you using?

**Comment by fliperama00** [comment]
HDA Intel (CedarTrail)

**Comment by spl237** [comment]
If you switch to the internal HDMI or Analog audio devices, does mute work properly?

**Comment by spl237** [comment]
Ah - are you running the Raspberry Pi Desktop for i386 on a laptop or similar? Not on a Pi?

Looking online, there are known issues with the CedarTrail driver - probably more useful to raise an issue agains the driver itself on Debian; it's not something we'd be able to investigate, as we don't have the hardware.

**Comment by fliperama00** [comment]
Yes, I am. Btw, just for the record, the problem was pulseaudio. It seems that it doesn't use the same command to mute and unmute. So, only alsa gets unmuted.

**Comment by spl237** [comment]
You must be using a very old version - we stopped using PulseAudio at least a year ago. Suggest you upgrade to the latest version - it's still on Stretch at the moment, but we'll have a Buster version available in the next couple of months.
