### ISSUE TITLE
Pi desktop volume control misspells analogue

### ISSUE THREAD

**Issue by andrum99** [raspberrypi-ui/lxplug-volume#5]
Right-clicking on the taskbar volume control gives me two options which allow me to select the active audio output:

Analog
HDMI

My localisation options are all set to UK/GB. In this case the first one should be analogue, not analog, per the Oxford English Dictionary - see https://www.lexico.com/en/definition/analogue.

**Comment by spl237** [comment]
In technical use, the shorter form of the word is usually preferred - hence "analog" is conventionally the opposite of "digital", both in the UK and the US. This is why GUIs have "dialog boxes" rather than "dialogue boxes", even on this side of the pond.

**Comment by andrum99** [comment]
I must just be old fashioned then 😛
